
trigger:
- master


variables:
- group: Docker-vars
- name: imageName
  value: octave-python

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'
      Python37:
        PYTHON_VERSION: '3.7'
  steps:
  - script: |
      docker build --build-arg PYTHON_VERSION=$(PYTHON_VERSION) -t $(dockerGroup)/$(imageName):py$(PYTHON_VERSION) .
    displayName: 'Build image'
  - script: |
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(dockerGroup)/$(imageName):py$(PYTHON_VERSION)
    displayName: 'Push container'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
